# Blueprint de Render: crea los DOS servicios (Render 1 y Render 2)
# https://render.com -> New -> Blueprint -> apuntar a este repositorio
# (este repo ES api-rest, sin subcarpetas: no se usa rootDir)
services:
  - type: web
    name: techstore-api-1
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: INSTANCE_NAME
        value: RENDER-1
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_REPLICA
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: SOAP_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: TWILIO_ADMIN_PHONE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM
        sync: false
  - type: web
    name: techstore-api-2
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: INSTANCE_NAME
        value: RENDER-2
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_REPLICA
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: SOAP_URL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: TWILIO_ADMIN_PHONE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM
        sync: false
